import React, { useState, useEffect } from 'react';

export default function AdminCreationsTracker({ API_BASE, showToast }) {
  const [generationLogs, setGenerationLogs] = useState([]);
  const [loading, setLoading] = useState(false);
  
  // Search & Filter States
  const [searchQuery, setSearchQuery] = useState('');
  const [sortOrder, setSortOrder] = useState('desc'); // 'desc' = newest first, 'asc' = oldest first

  // Modal Image Preview State
  const [previewImage, setPreviewImage] = useState(null);
  const [previewModalOpen, setPreviewModalOpen] = useState(false);

  // Fetch Generations Logs
  const fetchLogs = async (isInitial = false) => {
    if (isInitial) setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/api/admin/activity`, {
        headers: { 'Authorization': 'Bearer admin-auth-token-123' }
      });
      if (res.ok) {
        const data = await res.json();
        setGenerationLogs(data.data || []);
      } else {
        showToast('Failed to fetch activity logs.', 'error');
      }
    } catch (err) {
      if (isInitial) showToast('Network error while loading logs.', 'error');
    } finally {
      if (isInitial) setLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs(true);
    const interval = setInterval(() => {
      fetchLogs(false);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  // Filter and sort records
  const getFilteredLogs = () => {
    let filtered = [...generationLogs];

    // Search query filter
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(log => 
        (log.user_name && log.user_name.toLowerCase().includes(query)) ||
        (log.user_email && log.user_email.toLowerCase().includes(query)) ||
        (log.poster_title && log.poster_title.toLowerCase().includes(query))
      );
    }

    // Sort order
    filtered.sort((a, b) => {
      const dateA = new Date(a.generated_date);
      const dateB = new Date(b.generated_date);
      return sortOrder === 'desc' ? dateB - dateA : dateA - dateB;
    });

    return filtered;
  };

  const filteredLogs = getFilteredLogs();

  // Export to CSV
  const handleExportCSV = () => {
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Date,User Name,User Email,Poster Template,Credits Used\n";
    filteredLogs.forEach(row => {
      const date = new Date(row.generated_date).toLocaleString().replace(/,/g, '');
      const name = `"${row.user_name}"`;
      const email = `"${row.user_email}"`;
      const title = `"${row.poster_title}"`;
      const credits = row.credits_used;
      csvContent += `${date},${name},${email},${title},${credits}\n`;
    });
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "filtered_creations_report.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast('Exported report successfully.', 'success');
  };

  // Open Preview Modal
  const openPreview = (log) => {
    const userParam = log.user_id ? `&userId=${log.user_id}` : '';
    const imgUrl = `${API_BASE}/api/templates/thumbnail/${log.poster_image}?month=July${userParam}`;
    setPreviewImage({
      url: imgUrl,
      title: log.poster_title,
      user: log.user_name,
      email: log.user_email,
      date: new Date(log.generated_date).toLocaleString()
    });
    setPreviewModalOpen(true);
  };

  return (
    <section className="view-pane creations-tracker-pane">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <h1 className="headline-md" style={{ marginBottom: '4px' }}>Creations Tracking Log</h1>
          <p className="body-sm text-secondary">Monitor personalized posters generated by tax professionals on the platform.</p>
        </div>
        <button className="btn btn-primary" onClick={handleExportCSV}>
          <svg xmlns="http://www.w3.org/2000/svg" height="18" viewBox="0 -960 960 960" width="18" fill="currentColor" style={{ marginRight: '6px' }}><path d="M480-320 280-520l56-58 104 104v-326h80v326l104-104 56 58-200 200ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z"/></svg>
          Export CSV Report
        </button>
      </div>

      {/* Filter and Search Bar */}
      <div className="card" style={{ marginBottom: '24px', padding: '16px' }}>
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', alignItems: 'center' }}>
          <div style={{ flex: '1', minWidth: '250px' }}>
            <label className="input-label" style={{ display: 'block', marginBottom: '6px' }}>Search Creations</label>
            <input 
              type="text" 
              className="form-input" 
              style={{ width: '100%', padding: '8px 12px', fontSize: '13px' }} 
              placeholder="Search by practitioner name, email, or template name..." 
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
            />
          </div>

          <div style={{ width: '150px' }}>
            <label className="input-label" style={{ display: 'block', marginBottom: '6px' }}>Sorting</label>
            <select 
              className="form-select" 
              style={{ width: '100%', padding: '8px 12px' }}
              value={sortOrder}
              onChange={e => setSortOrder(e.target.value)}
            >
              <option value="desc">Newest First</option>
              <option value="asc">Oldest First</option>
            </select>
          </div>

          <div style={{ display: 'flex', alignItems: 'flex-end', height: '100%', paddingTop: '18px' }}>
            <button className="btn btn-outline btn-sm" onClick={() => { setSearchQuery(''); setSortOrder('desc'); }}>
              Reset Filters
            </button>
          </div>
        </div>
      </div>

      {/* Logs Table */}
      <div className="card overflow-x">
        {loading ? (
          <div style={{ textAlign: 'center', padding: '40px', color: 'var(--secondary)' }}>
            ⏳ Loading activity logs...
          </div>
        ) : filteredLogs.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px', color: 'var(--secondary)' }}>
            No generation activity records matched your criteria.
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Date & Time</th>
                <th>Name</th>
                <th style={{ textAlign: 'center' }}>Credits Used</th>
              </tr>
            </thead>
            <tbody>
              {filteredLogs.map(log => (
                <tr 
                  key={log.id} 
                  onClick={() => openPreview(log)} 
                  style={{ cursor: 'pointer' }}
                  title="Click to view branded poster preview"
                >
                  <td style={{ whiteSpace: 'nowrap' }}>
                    {new Date(log.generated_date).toLocaleDateString(undefined, { 
                      year: 'numeric', month: 'short', day: 'numeric' 
                    })}<br />
                    <span style={{ fontSize: '11px', color: 'var(--secondary)' }}>
                      {new Date(log.generated_date).toLocaleTimeString(undefined, {
                        hour: '2-digit', minute: '2-digit'
                      })}
                    </span>
                  </td>
                  <td>
                    <strong>{log.user_name}</strong><br />
                    <code style={{ fontSize: '11px', color: 'var(--secondary)' }}>{log.user_email}</code>
                  </td>
                  <td style={{ textAlign: 'center' }}>
                    <span className="badge badge-danger">-{log.credits_used} credit</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Modal Preview */}
      {previewModalOpen && previewImage && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100vw',
          height: '100vh',
          backgroundColor: 'rgba(15, 23, 42, 0.75)',
          backdropFilter: 'blur(4px)',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          zIndex: 9999,
          padding: '20px'
        }} onClick={() => setPreviewModalOpen(false)}>
          <div style={{
            backgroundColor: 'var(--surface-container-lowest)',
            border: '1px solid var(--border-color)',
            borderRadius: '12px',
            maxWidth: '500px',
            width: '100%',
            padding: '24px',
            position: 'relative',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            animation: 'fadeIn 0.2s ease'
          }} onClick={e => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h3 style={{ margin: 0 }}>Creation Preview</h3>
              <button 
                style={{ background: 'none', border: 'none', fontSize: '24px', cursor: 'pointer', color: 'var(--secondary)' }}
                onClick={() => setPreviewModalOpen(false)}
              >
                &times;
              </button>
            </div>
            
            <div style={{ textAlign: 'center', marginBottom: '16px', backgroundColor: 'var(--surface-container-low)', padding: '12px', borderRadius: '8px' }}>
              <img 
                src={previewImage.url} 
                alt="Branded Poster Output" 
                style={{ maxWidth: '100%', maxHeight: '450px', objectFit: 'contain', borderRadius: '6px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }} 
              />
            </div>

            <div style={{ fontSize: '13px', borderTop: '1px solid var(--border-color)', paddingTop: '12px' }}>
              <div style={{ marginBottom: '6px' }}><strong>Template:</strong> {previewImage.title}</div>
              <div style={{ marginBottom: '6px' }}><strong>Practitioner:</strong> {previewImage.user}</div>
              <div style={{ marginBottom: '6px' }}><strong>Email:</strong> {previewImage.email}</div>
              <div><strong>Generated Date:</strong> {previewImage.date}</div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
